name: untitled
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.6.1
  recase: ^4.1.0
  flutter_svg: ^2.0.0+1
  http: ^0.13.5
  connectivity_plus: ^3.0.3
  get: ^4.6.5
  intl: ^0.18.0
  shared_preferences: ^2.0.17
  hive:
  hive_flutter:
  lottie: ^2.2.0
  flutter_staggered_grid_view: ^0.6.2
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/anim/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/sounds/
    - assets/videos/

  fonts:

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

